import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';

const PORT=Number(process.env.PORT||8787), DATA_FILE=process.env.PEAOS_CERT_DB||'./certificates.json', KEY_FILE=process.env.PEAOS_CERT_KEY||'./issuer-ed25519-private.pem';
const GITHUB_TOKEN=process.env.PEAOS_GITHUB_TOKEN||'';
const GITHUB_OWNER=process.env.PEAOS_GITHUB_OWNER||'alexiusandromedavsgalaxia-lgtm';
const GITHUB_REPO=process.env.PEAOS_GITHUB_REPO||'peaOS.Officialy-certificates';
const GITHUB_BRANCH=process.env.PEAOS_GITHUB_BRANCH||'main';
const REGISTRY_PATH=process.env.PEAOS_GITHUB_REGISTRY_PATH||'registry.json';
const REGISTRY_ISSUER='peaOS.Officialy-certificates';
const REGISTRY_VERSION=2;
let privateKey,publicKey;
try{privateKey=crypto.createPrivateKey(fs.readFileSync(KEY_FILE));publicKey=crypto.createPublicKey(privateKey);}catch{({privateKey,publicKey}=crypto.generateKeyPairSync('ed25519'));fs.writeFileSync(KEY_FILE,privateKey.export({type:'pkcs8',format:'pem'}),{mode:0o600});}
const issuerKeyId=crypto.createHash('sha256').update(publicKey.export({type:'spki',format:'der'})).digest('hex').slice(0,32);
let state=new Map();try{const saved=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));for(const r of saved)state.set(r.certificate.certificate_id,r);}catch{}
function persist(){fs.writeFileSync(DATA_FILE,JSON.stringify([...state.values()],null,2),{mode:0o600});}
function json(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':data.length,'cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});res.end(data);}
function canonical(c){return JSON.stringify({version:c.version,certificate_id:c.certificate_id,issuer_key_id:c.issuer_key_id,issued_at:c.issued_at,expires_at:c.expires_at,serial:c.serial,application_count:c.application_count,distribution:c.distribution,origin:c.origin,applications:c.applications.map(a=>({package_hash:a.package_hash}))});}
function sign(c){return crypto.sign(null,Buffer.from(canonical(c)),privateKey).toString('base64');}
function signatureValid(c){try{return crypto.verify(null,Buffer.from(canonical(c)),publicKey,Buffer.from(c.signature,'base64'));}catch{return false;}}
function certificateState(r){const c=r.certificate,n=Math.floor(Date.now()/1000);if(r.revoked)return{active:false,reason:'revoked',checked_at:n};if(n<c.issued_at||n>=c.expires_at)return{active:false,reason:'expired',checked_at:n};if(r.origin!==c.origin)return{active:false,reason:'origin_mismatch',checked_at:n};if(!signatureValid(c))return{active:false,reason:'signature_invalid',checked_at:n};return{active:true,reason:'active',checked_at:n};}
function validOrigin(o){try{const u=new URL(o);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}}
function verifyShape(c){if(!c||c.version!==2)return'invalid_version';if(!/^[a-f0-9]{32}$/.test(c.certificate_id))return'invalid_certificate_id';if(c.issuer_key_id!==issuerKeyId)return'issuer_mismatch';if(!Number.isSafeInteger(c.issued_at)||!Number.isSafeInteger(c.expires_at)||!Number.isSafeInteger(c.serial)||c.serial<=0)return'invalid_number';if(c.expires_at<=c.issued_at||c.expires_at-c.issued_at>90*24*60*60)return'invalid_lifetime';if(!Number.isInteger(c.application_count)||c.application_count<1||c.application_count>5)return'invalid_application_count';if(c.distribution!=='web'||!validOrigin(c.origin))return'invalid_web_distribution';if(!Array.isArray(c.applications)||c.applications.length!==c.application_count)return'invalid_bindings';for(const a of c.applications)if(!/^[a-f0-9]{64}$/.test(a.package_hash))return'invalid_package_hash';return null;}
async function body(req){let d='';for await(const c of req){d+=c;if(d.length>65536)throw new Error('body_too_large')}return JSON.parse(d);}
function authorized(req){const token=process.env.PEAOS_CERT_ADMIN_TOKEN||'';return token&&req.headers.authorization===`Bearer ${token}`;}
function nextSerial(){const serial=crypto.randomBytes(6).readUIntBE(0,6);return serial===0?1:serial;}
async function github(path,options={}){if(!GITHUB_TOKEN)throw new Error('github_backend_not_configured');const response=await fetch(`https://api.github.com${path}`,{...options,headers:{Accept:'application/vnd.github+json','Authorization':`Bearer ${GITHUB_TOKEN}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||`github_http_${response.status}`);return data;}
async function readRegistry(){const data=await github(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}/contents/${REGISTRY_PATH}?ref=${encodeURIComponent(GITHUB_BRANCH)}`);const raw=Buffer.from(data.content||'','base64').toString('utf8');const registry=JSON.parse(raw);if(registry.schema!==1||registry.issuer!==REGISTRY_ISSUER||registry.peaOS_certificate_version!==REGISTRY_VERSION||!Array.isArray(registry.certificates))throw new Error('github_registry_invalid');return{registry,sha:data.sha};}
async function writeRegistry(registry,sha,message){const content=Buffer.from(`${JSON.stringify(registry,null,2)}\n`).toString('base64');return github(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}/contents/${REGISTRY_PATH}`,{method:'PUT',body:JSON.stringify({message,content,branch:GITHUB_BRANCH,sha})});}
function registryEntry(input,c){return{id:c.certificate_id,name:input.name,origin:c.origin,distribution:'WebDistribution',status:'Active',issued_at:c.issued_at,expires_at:c.expires_at,issuer_key_id:c.issuer_key_id,certificate_version:c.version,serial:c.serial};}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,204,{});const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&url.pathname==='/v1/issuer')return json(res,200,{protocol:2,issuer_key_id:issuerKeyId,algorithm:'Ed25519',public_key:publicKey.export({type:'spki',format:'der'}).toString('base64')});const match=url.pathname.match(/^\/v1\/certificates\/([a-f0-9]{32})$/);if(req.method==='GET'&&match){const r=state.get(match[1]);if(!r)return json(res,404,{active:false,reason:'unknown_certificate'});return json(res,200,{certificate:r.certificate,...certificateState(r),provenance:{issuer_key_id:issuerKeyId,origin:r.origin,serial:r.certificate.serial,package_hashes:r.certificate.applications.map(a=>a.package_hash)}});}if(req.method==='POST'&&url.pathname==='/v1/certificates/issue'){if(!authorized(req))return json(res,401,{active:false,reason:'unauthorized'});let input;try{input=await body(req);}catch{return json(res,400,{active:false,reason:'invalid_json'});}const now=Math.floor(Date.now()/1000),c={version:2,certificate_id:crypto.randomBytes(16).toString('hex'),issuer_key_id:issuerKeyId,issued_at:now,expires_at:Math.min(input.expires_at||now+90*24*60*60,now+90*24*60*60),serial:nextSerial(),application_count:input.application_count,distribution:'web',origin:input.origin,applications:input.applications||[]};const error=verifyShape(c);if(error)return json(res,400,{active:false,reason:error});c.signature=sign(c);const r={certificate:c,origin:c.origin,revoked:false};state.set(c.certificate_id,r);persist();return json(res,201,{certificate_id:c.certificate_id,...certificateState(r),certificate:c});}
if(req.method==='POST'&&url.pathname==='/v1/registrations'){let input;try{input=await body(req);}catch{return json(res,400,{ok:false,reason:'invalid_json'});}if(typeof input.name!=='string'||!input.name.trim()||input.name.length>120)return json(res,400,{ok:false,reason:'invalid_name'});if(!validOrigin(input.origin))return json(res,400,{ok:false,reason:'invalid_origin'});if(input.distribution!=='Local'&&input.distribution!=='WebDistribution')return json(res,400,{ok:false,reason:'invalid_distribution'});if(input.distribution==='Local')return json(res,400,{ok:false,reason:'local_certificates_require_signed_build_flow'});if(!GITHUB_TOKEN)return json(res,503,{ok:false,reason:'github_backend_not_configured'});try{const now=Math.floor(Date.now()/1000),c={version:2,certificate_id:crypto.randomBytes(16).toString('hex'),issuer_key_id:issuerKeyId,issued_at:now,expires_at:now+90*24*60*60,serial:nextSerial(),application_count:1,distribution:'web',origin:input.origin,applications:[{package_hash:crypto.createHash('sha256').update(input.origin).digest('hex')}]};c.signature=sign(c);const r={certificate:c,origin:c.origin,revoked:false};const {registry,sha}=await readRegistry();if(registry.certificates.some(x=>x.id===c.certificate_id))return json(res,409,{ok:false,reason:'certificate_already_registered'});const entry=registryEntry(input,c);registry.certificates.push(entry);await writeRegistry(registry,sha,`Register certificate ${c.certificate_id}`);state.set(c.certificate_id,r);persist();return json(res,201,{ok:true,certificate_id:c.certificate_id,status:'Active',certificate:c,registry_entry:entry});}catch(error){return json(res,502,{ok:false,reason:error.message})}}
const revoke=url.pathname.match(/^\/v1\/certificates\/([a-f0-9]{32})\/revoke$/);if(req.method==='POST'&&revoke){if(!authorized(req))return json(res,401,{active:false,reason:'unauthorized'});const r=state.get(revoke[1]);if(!r)return json(res,404,{active:false,reason:'unknown_certificate'});r.revoked=true;persist();return json(res,200,{active:false,reason:'revoked'});}return json(res,404,{error:'not_found'});});
server.listen(PORT,()=>console.log(`peaOS certificate service listening on :${PORT}`));
