import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';

const PORT=Number(process.env.PORT||8787), DATA_FILE=process.env.PEAOS_CERT_DB||'./certificates.json', KEY_FILE=process.env.PEAOS_CERT_KEY||'./issuer-ed25519-private.pem', ADMIN_TOKEN=process.env.PEAOS_CERT_ADMIN_TOKEN||'';
let privateKey,publicKey;
try{privateKey=crypto.createPrivateKey(fs.readFileSync(KEY_FILE));publicKey=crypto.createPublicKey(privateKey);}catch{({privateKey,publicKey}=crypto.generateKeyPairSync('ed25519'));fs.writeFileSync(KEY_FILE,privateKey.export({type:'pkcs8',format:'pem'}),{mode:0o600});}
const issuerKeyId=crypto.createHash('sha256').update(publicKey.export({type:'spki',format:'der'})).digest('hex').slice(0,32);
let state=new Map();try{const saved=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));for(const r of saved)state.set(r.certificate.certificate_id,r);}catch{}
function persist(){fs.writeFileSync(DATA_FILE,JSON.stringify([...state.values()],null,2),{mode:0o600});}
function json(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':data.length,'cache-control':'no-store'});res.end(data);}
function canonical(c){return JSON.stringify({version:c.version,certificate_id:c.certificate_id,issuer_key_id:c.issuer_key_id,issued_at:c.issued_at,expires_at:c.expires_at,serial:c.serial,application_count:c.application_count,distribution:c.distribution,origin:c.origin,applications:c.applications.map(a=>({package_hash:a.package_hash}))});}
function sign(c){return crypto.sign(null,Buffer.from(canonical(c)),privateKey).toString('base64');}
function signatureValid(c){try{return crypto.verify(null,Buffer.from(canonical(c)),publicKey,Buffer.from(c.signature,'base64'));}catch{return false;}}
function certificateState(r){const c=r.certificate,n=Math.floor(Date.now()/1000);if(r.revoked)return{active:false,reason:'revoked',checked_at:n};if(n<c.issued_at||n>=c.expires_at)return{active:false,reason:'expired',checked_at:n};if(r.origin!==c.origin)return{active:false,reason:'origin_mismatch',checked_at:n};if(!signatureValid(c))return{active:false,reason:'signature_invalid',checked_at:n};return{active:true,reason:'active',checked_at:n};}
function validOrigin(o){try{const u=new URL(o);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}}
function verifyShape(c){if(!c||c.version!==2)return'invalid_version';if(!/^[a-f0-9]{32}$/.test(c.certificate_id))return'invalid_certificate_id';if(c.issuer_key_id!==issuerKeyId)return'issuer_mismatch';if(!Number.isSafeInteger(c.issued_at)||!Number.isSafeInteger(c.expires_at)||!Number.isSafeInteger(c.serial)||c.serial<=0)return'invalid_number';if(c.expires_at<=c.issued_at||c.expires_at-c.issued_at>90*24*60*60)return'invalid_lifetime';if(!Number.isInteger(c.application_count)||c.application_count<1||c.application_count>5)return'invalid_application_count';if(c.distribution!=='web'||!validOrigin(c.origin))return'invalid_web_distribution';if(!Array.isArray(c.applications)||c.applications.length!==c.application_count)return'invalid_bindings';for(const a of c.applications)if(!/^[a-f0-9]{64}$/.test(a.package_hash))return'invalid_package_hash';return null;}
async function body(req){let d='';for await(const c of req)d+=c;return JSON.parse(d);}
function authorized(req){return ADMIN_TOKEN&&req.headers.authorization===`Bearer ${ADMIN_TOKEN}`;}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&url.pathname==='/v1/issuer')return json(res,200,{protocol:2,issuer_key_id:issuerKeyId,algorithm:'Ed25519',public_key:publicKey.export({type:'spki',format:'der'}).toString('base64')});const match=url.pathname.match(/^\/v1\/certificates\/([a-f0-9]{32})$/);if(req.method==='GET'&&match){const r=state.get(match[1]);if(!r)return json(res,404,{active:false,reason:'unknown_certificate'});return json(res,200,{certificate:r.certificate,...certificateState(r),provenance:{issuer_key_id:issuerKeyId,origin:r.origin,serial:r.certificate.serial,package_hashes:r.certificate.applications.map(a=>a.package_hash)}});}if(req.method==='POST'&&url.pathname==='/v1/certificates/issue'){if(!authorized(req))return json(res,401,{active:false,reason:'unauthorized'});let input;try{input=await body(req);}catch{return json(res,400,{active:false,reason:'invalid_json'});}const now=Math.floor(Date.now()/1000),c={version:2,certificate_id:crypto.randomBytes(16).toString('hex'),issuer_key_id:issuerKeyId,issued_at:now,expires_at:Math.min(input.expires_at||now+90*24*60*60,now+90*24*60*60),serial:crypto.randomInt(1,Number.MAX_SAFE_INTEGER),application_count:input.application_count,distribution:'web',origin:input.origin,applications:input.applications||[]};const error=verifyShape(c);if(error)return json(res,400,{active:false,reason:error});c.signature=sign(c);const r={certificate:c,origin:c.origin,revoked:false};state.set(c.certificate_id,r);persist();return json(res,201,{certificate_id:c.certificate_id,...certificateState(r),certificate:c});}const revoke=url.pathname.match(/^\/v1\/certificates\/([a-f0-9]{32})\/revoke$/);if(req.method==='POST'&&revoke){if(!authorized(req))return json(res,401,{active:false,reason:'unauthorized'});const r=state.get(revoke[1]);if(!r)return json(res,404,{active:false,reason:'unknown_certificate'});r.revoked=true;persist();return json(res,200,{active:false,reason:'revoked'});}return json(res,404,{error:'not_found'});});
server.listen(PORT,()=>console.log(`peaOS certificate service listening on :${PORT}`));
