#include "ui.hpp"
#include "console.hpp"

namespace ui {
namespace { Theme g_theme{0x0B0D12,0x151922,0x1D2230,0x7C6CFF,0xF7F8FC,0x9299AA,18,14};uint32_t g_width=1024,g_height=768; }
void init(uint32_t width,uint32_t height){g_width=width?width:1024;g_height=height?height:768;}
const Theme& theme(){return g_theme;}uint32_t width(){return g_width;}uint32_t height(){return g_height;}
const char* style_name(){return "peaOS Aurora Glass";}
void render_home(){console::write_line("");console::write_line("+================================================================+");console::write_line("| peaOS 1 Beta 1                 Aurora Glass              20:24 |");console::write_line("+----------------------+-----------------------------------------+");console::write_line("|  SEARCH              |  Welcome back                           |");console::write_line("|                      |                                         |");console::write_line("|  Favorites           |  +-----------+ +-----------+           |");console::write_line("|  Files   Browser     |  |  Files    | |  Settings |           |");console::write_line("|  Notes   Terminal    |  +-----------+ +-----------+           |");console::write_line("|                      |                                         |");console::write_line("|  System              |  +-----------+ +-----------+           |");console::write_line("|  Software Center     |  |  Browser  | |  Terminal |           |");console::write_line("|  Task Manager        |  +-----------+ +-----------+           |");console::write_line("|  System Monitor      |                                         |");console::write_line("|                      |  Recent applications                   |");console::write_line("|  X90                 |  Settings  Files  Notes  Development  |");console::write_line("|  Fusion  TimeMachine |                                         |");console::write_line("|  Morph               |  peaOS Aurora Glass  •  x86_64        |");console::write_line("+----------------------+-----------------------------------------+");}
}
